version: "3.9"
services:
  db:
    image: postgres:11.12
    environment:
      POSTGRES_DB: dm2_staging
      POSTGRES_USER: dm2_dev_user
      POSTGRES_PASSWORD: dm2_dev_password
    command: postgres -c listen_addresses='*'
    volumes:
      - ./tmp/dev-db:/var/lib/postgresql/data
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && cd /opt/app && bundle exec foreman start -f Procfile.dev"
    ports:
      - "3001:3001"
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    environment: # May be overridden by values in .env
      DATABASE_URL: postgres://dm2_dev_user:dm2_dev_password@db
      RACK_ENV: development
      RAILS_ENV: development